{
 "title": "StreamX Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(up,kubernetes_namespace)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(up{kubernetes_namespace=\"$namespace\"},application)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{application=~\"$application\", cluster=\"$cluster\"},instance)"
    }
   },
   {
    "name": "channel",
    "label": "Channel",
    "query": {
     "query": "label_values(quarkus_messaging_message_count_total{application=\"$application\"},channel)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  { "title": "Stores(Quasar)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Messages in store",
   "type": "stat",
   "description": "Displays the total number of unique messages currently stored, counted by unique keys. The count includes all messages, regardless of action type or payload presence.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quasar_store_unique_keys_count_total{application=~\"$application\", instance=~\"$instance\", channel=~\"$channel\"}",
     "legendFormat": "{store:{{store}}, instance:{{instance}}}"
    }
   ]
  },
  {
   "title": "IDelta of unique messages in store",
   "type": "timeseries",
   "description": "Displays how the total number of unique messages currently stored increase in time using IDelta function.\n\nThe messages are counted by unique keys. The count includes all messages, regardless of action type or payload presence.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "idelta(quasar_store_unique_keys_count_total{application=~\"$application\", instance=~\"$instance\", channel=~\"$channel\"}[1m])",
     "legendFormat": "{store:{{store}}, instance:{{instance}}}"
    }
   ]
  },
  {
   "title": "Published messages in store",
   "type": "stat",
   "description": "Displays the total number of unique messages currently stored, counted by unique keys and having ACTION==PUBLISHED. \n\nThe number decreases when store received message new version with ACTION==UNPUBLISH ",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quasar_store_messages_size_by_action_gauge{application=~\"$application\", instance=~\"$instance\", channel=~\"$channel\"}",
     "legendFormat": "{store:{{store}}, instance:{{instance}}}"
    }
   ]
  },
  {
   "title": "IDelta of published messages in store",
   "type": "timeseries",
   "description": "Displays how the number of unique messages currently stored changes over time using idelta function. \n\nMessages are counted by unique keys and having ACTION==PUBLISHED\n\nThe number decreases when store received message new version with ACTION==UNPUBLISH ",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "idelta(quasar_store_messages_size_by_action_gauge{application=~\"$application\", instance=~\"$instance\", channel=~\"$channel\"}[1m])",
     "legendFormat": "{store:{{store}}, instance:{{instance}}}"
    }
   ]
  },
  {
   "title": "Messages having payload in store",
   "type": "stat",
   "description": "Displays the total number of unique messages currently stored, counted by unique keys and having payload not null. \n\nThe number decreases when store received message new version with null payload",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quasar_store_messages_size_by_payload_gauge{application=~\"$application\", instance=~\"$instance\", channel=~\"$channel\"}",
     "legendFormat": "{store:{{store}}, instance:{{instance}}}"
    }
   ]
  },
  {
   "title": "IDelta of messages having payload in store",
   "type": "timeseries",
   "description": "Displays how the number of unique messages currently stored changes over time using idelta function.\n\nMessages are counted by unique keys and having not null payload\n\nThe number decreases when store received message new version with null payload\n",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "idelta(quasar_store_messages_size_by_payload_gauge{application=~\"$application\", instance=~\"$instance\", channel=~\"$channel\"}[1m])",
     "legendFormat": "{store:{{store}}, instance:{{instance}}}"
    }
   ]
  },
  {
   "title": "Published messages in store difference between instances",
   "type": "timeseries",
   "description": "Shows the difference of messages number between the same store on application instances.\n\nThe value is: max store size from each instance - min store size from each instance.\n\nPublished Messages is the total number of unique messages currently stored, counted by unique keys and having ACTION==PUBLISHED.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "max by(application, store) (quasar_store_messages_size_by_action_gauge{application=~\"$application\", channel=~\"$channel\"}) - min by(application, store) (quasar_store_messages_size_by_action_gauge{application=~\"$application\", channel=~\"$channel\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages having payload in store difference between instances",
   "type": "timeseries",
   "description": "Shows the difference of messages number between the same store on application instances.\n\nThe value is: max store size from each instance - min store size from each instance.\n\nMessages having payload is the total number of unique messages currently stored, counted by unique keys and having payload not null.\n\n",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "max by(application, store) (quasar_store_messages_size_by_payload_gauge{application=~\"$application\", channel=~\"$channel\"}) - min by(application, store) (quasar_store_messages_size_by_payload_gauge{application=~\"$application\", channel=~\"$channel\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IDelta of outdated messages by store",
   "type": "timeseries",
   "description": "Shows outdated messages in time using IDelta function.\n\nOutdated messages is when incoming message is older than message already present on the store. \n\nThe age of message is calculated using message timestamp",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "idelta(quasar_store_outdated_messages_count_total{application=~\"$application\", instance=~\"$instance\", channel=~\"$channel\"}[$__interval])",
     "legendFormat": "{store:{{store}}, instance:{{instance}}}"
    }
   ]
  },
  { "title": "Replicas(Kubernetes)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Not available replicas",
   "type": "timeseries",
   "description": "Difference between requested replicas number and available",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{kubernetes_namespace=\"$namespace\"} - kube_deployment_status_replicas_available{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Available replicas",
   "type": "timeseries",
   "description": "Shows available replicas for each application",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  { "title": "Traffic(Quarkus)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "IDelta of http requests ",
   "type": "timeseries",
   "description": "Displays how the number of http requests changes over time using idelta function.\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "idelta(http_server_requests_seconds_count{kubernetes_namespace=~\"$namespace\", application=~\"$application\", instance=~\"$instance\"}[1m])",
     "legendFormat": "{ uri:{{uri}}, status: {{status}}, method: {{method}},  instance: {{instance}}, application:{{application}}}"
    }
   ]
  },
  {
   "title": "IDelta of messages ACK",
   "type": "timeseries",
   "description": "Displays how the number of acked messages changes over time using idelta function.\n\nBased on quarkus_messaging_message_acks_total metric",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "idelta(quarkus_messaging_message_acks_total{application=~\"$application\", instance=~\"$instance\", channel=~\"$channel\"}[1m])",
     "legendFormat": "{channel:{{channel}}, instance:{{instance}}}"
    }
   ]
  },
  {
   "title": "IDelta of messages NACK",
   "type": "timeseries",
   "description": "Displays how the number of nacked messages changes over time using idelta function.\n\nBased on quarkus_messaging_message_failures_total metric.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "idelta(quarkus_messaging_message_failures_total{application=~\"$application\", instance=~\"$instance\", channel=~\"$channel\"}[1m])",
     "legendFormat": "{channel:{{channel}}, instance:{{instance}}}"
    }
   ]
  },
  {
   "title": "Max duration of message processing",
   "type": "timeseries",
   "description": "Shows max time of processing message in service. \n\nBased on quarkus_messaging_message_duration_seconds_max metric. \n\nThe value is measured from message processing function start until message is Ack or NAck.\n\nThe time of fetching message from broker or storing message in processing waiting queue is not included into this metric.\n\nMax value is calculated using 60s slicing window. It means the value is in the calculation range in >= 120 s. \n\nThe calculation algorithm based on \"ticks\". Prometheus samples metrics. The combination of this approaches can leads to little shift of change the values in grafana dashboard  ",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "quarkus_messaging_message_duration_seconds_max{application=~\"$application\", instance=~\"$instance\", channel=~\"$channel\"}",
     "legendFormat": "{channel:{{channel}}, instance:{{instance}}}"
    }
   ]
  },
  {
   "title": "Average duration of message processing",
   "type": "timeseries",
   "description": "Shows average time of processing message.\n\nThe value is calculated dividing sum of all messages processing time by count of all messages processed since instance is up.\n\nBased on quarkus_messaging_message_duration_seconds_sum and quarkus_messaging_message_duration_seconds_count metrics. \n\nThe value is measured from message processing function start until message is Ack or NAck.\n\nThe time of fetching message from broker or storing message in processing waiting queue is not included into this metric.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "quarkus_messaging_message_duration_seconds_sum{application=~\"$application\", instance=~\"$instance\", channel=~\"$channel\"} / quarkus_messaging_message_duration_seconds_count{application=~\"$application\", instance=~\"$instance\", channel=~\"$channel\"}",
     "legendFormat": "{channel:{{channel}}, instance:{{instance}}}"
    }
   ]
  }
 ]
}