cluster:
  create: true
  spec:
    global:
      name: pulsar
      image: apachepulsar/pulsar:4.0.0
      restartOnConfigMapChange: true
    zookeeper:
      replicas: 3
      dataVolume:
        name: data
        size: 100M
      resources:
        requests:
          cpu: "0.1"
          memory: "256Mi"
    bookkeeper:
      replicas: 3
      volumes:
        journal:
          size: 10Gi
        ledgers:
          size: 120Gi
      resources:
        requests:
          cpu: "0.4"
          memory: "2Gi"
    broker:
      replicas: 3
      config:
        managedLedgerDefaultEnsembleSize: "2"
        managedLedgerDefaultWriteQuorum: "2"
        managedLedgerDefaultAckQuorum: "2"
        compactionServiceFactoryClassName: "org.apache.pulsar.compaction.EventTimeCompactionServiceFactory"
      resources:
        requests:
          cpu: "0.4"
        memory: "1Gi"
    proxy:
      replicas: 0
    autorecovery:
      replicas: 0
    bastion:
      replicas: 0
    functionsWorker:
      replicas: 0