storage:
  trace:
    backend: s3
    s3:
      access_key: '${accessKeyId}'
      secret_key: '${secretAccessKey}'
      bucket: 'tempo-traces'
      endpoint: 'minio.minio.svc.cluster.local:9000'
      insecure: true

traces:
  otlp:
    grpc:
      enabled: true

ingester:
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: "s3-access-keys"
distributor:
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: "s3-access-keys"
metricsGenerator:
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: "s3-access-keys"
compactor:
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: "s3-access-keys"
querier:
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: "s3-access-keys"
queryFrontend:
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: "s3-access-keys"