# Copyright 2025 Dynamic Solutions Sp. z o.o. sp.k.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

cluster:
  create: true
  spec:
    global:
      name: pulsar
      image: apachepulsar/pulsar:4.0.0
      restartOnConfigMapChange: true
    zookeeper:
      replicas: 1
      dataVolume:
        name: data
        size: 100M
      resources:
        requests:
          cpu: "0.1"
          memory: "256Mi"
    bookkeeper:
      replicas: 1
      volumes:
        journal:
          size: 5Gi
        ledgers:
          size: 20Gi
      resources:
        requests:
          cpu: "0.4"
          memory: "2Gi"
    broker:
      replicas: 1
      config:
        managedLedgerDefaultEnsembleSize: "1"
        managedLedgerDefaultWriteQuorum: "1"
        managedLedgerDefaultAckQuorum: "1"
        compactionServiceFactoryClassName: "org.apache.pulsar.compaction.EventTimeCompactionServiceFactory"
      resources:
        requests:
          cpu: "0.4"
        memory: "1Gi"
    proxy:
      replicas: 0
    autorecovery:
      replicas: 0
    bastion:
      replicas: 0
    functionsWorker:
      replicas: 0
