apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: "streamx-pod-monitor"
spec:
  labelLimit: 63
  labelNameLengthLimit: 511
  labelValueLengthLimit: 1023
  podMetricsEndpoints:
    - targetPort: 8080
      path: "/q/metrics"
      scheme: http
      interval: "10s"
      scrapeTimeout: "10s"
      relabelings:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - sourceLabels: [__meta_kubernetes_namespace]
          action: replace
          targetLabel: kubernetes_namespace
        - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
          action: replace
          targetLabel: job
        - sourceLabels: [__meta_kubernetes_pod_name]
          action: replace
          targetLabel: kubernetes_pod_name
        - sourceLabels: [__meta_kubernetes_pod_name]
          action: replace
          targetLabel: instance
        - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
          action: replace
          targetLabel: application
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
      - { key: app.kubernetes.io/managed-by, operator: In, values: ["streamx-delivery-controller", "streamx-processing-controller", "streamx-ingestion-controller"] }
      - { key: app.kubernetes.io/component, operator: In, values: ["delivery", "processing", "ingestion"] }