admin:
  existingSecret: "grafana-admin"
  userKey: admin-user
  passwordKey: admin-password

sidecar:
  dashboards:
    enabled: true
    folderAnnotation: dashboard_folder
    label: grafana_dashboard
    labelValue: "1"
    enableNewTablePanelSyntax: false
    annotations: {}
    multicluster:
      global:
        enabled: false
      etcd:
        enabled: false
    provider:
      allowUiUpdates: false
      foldersFromFilesStructure: true
  datasources:
    enabled: true
    label: grafana_datasource
    labelValue: "1"