replicas: 1
# Minio requires 2 to 16 drives for erasure code (drivesPerNode * replicas)
# https://docs.min.io/docs/minio-erasure-code-quickstart-guide
# Since we only have 1 replica, that means 2 drives must be used.
drivesPerNode: 2
users:
  - accessKey: minio-user
    existingSecret: s3-access-keys
    existingSecretKey: secretAccessKey
    policy: readwrite
buckets:
  - name: loki-chunks
    policy: none
    purge: false
  - name: loki-ruler
    policy: none
    purge: false
  - name: loki-admin
    policy: none
    purge: false
  - name: tempo-traces
    policy: none
    purge: false
  - name: mimir-blocks
    policy: none
    purge: false
  - name: mimir-ruler
    policy: none
    purge: false
  - name: mimir-alertmanager
    policy: none
    purge: false
persistence:
  size: 50Gi
resources:
  requests:
    cpu: 100m
    memory: 128Mi
