apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: "kaap-bookkeeper-pod-monitor"
spec:
  labelLimit: 63
  labelNameLengthLimit: 511
  labelValueLengthLimit: 1023
  podMetricsEndpoints:
    - targetPort: 8000
      path: "metrics"
      scheme: http
      interval: "10s"
      scrapeTimeout: "10s"
      relabelings:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - sourceLabels: [__meta_kubernetes_namespace]
          action: replace
          targetLabel: kubernetes_namespace
        - sourceLabels: [__meta_kubernetes_pod_label_component]
          action: replace
          targetLabel: job
        - sourceLabels: [__meta_kubernetes_pod_name]
          action: replace
          targetLabel: kubernetes_pod_name
        - sourceLabels: [__meta_kubernetes_pod_name]
          action: replace
          targetLabel: instance
        - sourceLabels: [__meta_kubernetes_pod_label_component]
          action: replace
          targetLabel: application
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: pulsar
      cluster: pulsar
      component: bookkeeper