name: "CI: Terraform verify"
on:
  - pull_request

jobs:
  fmt:
    name: "fmt"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 0.15.x

      - name: Terraform fmt
        run: terraform fmt -recursive -write=false -check -diff .

  validate:
    name: "validate"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_version: [1.0.x, 1.10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform ${{ matrix.terraform_version }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform_version }}

      - name: Validate root
        run: cd "${GITHUB_WORKSPACE}" && terraform init -backend=false && terraform validate -no-color

      - name: Validate modules
        run: for module in modules/*/; do cd "${GITHUB_WORKSPACE}/${module}" && terraform init -backend=false && terraform validate -no-color ; done